name: 'Invisible Character Detector'
description: 'Detects hidden Unicode, BiDi overrides, and Glassworm smuggling in source code.'
author: 'nealhar'
branding:
  icon: 'shield'
  color: 'red'

inputs:
  pattern:
    description: 'Glob pattern of files to scan (e.g., "**/*.rs" or "src/**/*")'
    required: true
    default: '**/*'
  json:
    description: 'Output results in JSON format (true/false)'
    required: false
    default: 'false'
  scan_bundles:
    description: 'Include dist/, build/, and out/ directories in the scan'
    required: false
    default: 'false'
  fail_on_skip:
    description: 'Exit with error code 2 if any files are unreadable'
    required: false
    default: 'false'
  verbose:
    description: 'Show details about ignored or unreadable files'
    required: false
    default: 'false'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.pattern }}
    - ${{ inputs.json == 'true' && '--json' || '' }}
    - ${{ inputs.scan_bundles == 'true' && '--scan-bundles' || '' }}
    - ${{ inputs.fail_on_skip == 'true' && '--fail-on-skip' || '' }}
    - ${{ inputs.verbose == 'true' && '--verbose' || '' }}